{
 "title": "marketplace-ci",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Database Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(marketplace_db_errors_total{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Marketplace DB errors"
    }
   ]
  },
  {
   "title": "Kafka Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(marketplace_kafka_errors_total{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "kafka errors"
    }
   ]
  },
  {
   "title": "Requests per minute by Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total_by_status_total{kubernetes_namespace=\"marketplace-ci\"}[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Retries ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(time_retries{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Time Retries"
    },
    {
     "expr": "sum(commit_retries{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Commit Retries"
    },
    {
     "expr": "sum(time_retries{kubernetes_namespace=\"marketplace-ci\"}) + sum(commit_retries{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Total Retries"
    }
   ]
  },
  {
   "title": "Archived Reports & Slices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(archived_fail_reports{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Archived Failed Reports"
    },
    {
     "expr": "sum(archived_success_reports{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Archived Successful Reports"
    },
    {
     "expr": "sum(archived_fail_reports{kubernetes_namespace=\"marketplace-ci\"}) + sum(archived_success_reports{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Total Archived Reports"
    },
    {
     "expr": "sum(archived_success_slices{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Archived Successful Report Slices"
    },
    {
     "expr": "sum(archived_fail_slices{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Archived Failed Report Slices"
    },
    {
     "expr": "sum(archived_success_slices{kubernetes_namespace=\"marketplace-ci\"}) + sum(archived_fail_slices{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Total Archived Report Slices"
    }
   ]
  },
  {
   "title": "Failed Reports",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(failed_validation{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Reports that failed validation"
    },
    {
     "expr": "sum(failed_download{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Reports that failed to download"
    },
    {
     "expr": "sum(invalid_reports{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Invalid reports "
    }
   ]
  },
  {
   "title": "Report Processing Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(report_processing_latency_sum{kubernetes_namespace=\"marketplace-ci\"})/sum(report_processing_latency_count{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Report Processing Latency Average"
    },
    {
     "expr": "sum(validation_latency_sum{kubernetes_namespace=\"marketplace-ci\"})/sum(validation_latency_count{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Validation Latency Average"
    }
   ]
  },
  {
   "title": "Report Uploads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(marketplace_message_uploads_total{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Total report uploads"
    },
    {
     "expr": "sum(rate(marketplace_message_uploads_total{kubernetes_namespace=\"marketplace-ci\"}[1m]))",
     "legendFormat": "Rate of report uploads per minute"
    },
    {
     "expr": "sum(increase(marketplace_message_uploads_total{kubernetes_namespace=\"marketplace-ci\"}[1m]))",
     "legendFormat": "Total report uploads per min"
    },
    {
     "expr": "sum(increase(marketplace_message_uploads_total{kubernetes_namespace=\"marketplace-ci\"}[1h]))",
     "legendFormat": "Total report uploads per hour"
    },
    {
     "expr": "sum(rate(marketplace_message_uploads_total{kubernetes_namespace=\"marketplace-ci\"}[1h]))",
     "legendFormat": "Rate of report uploads per hour"
    },
    {
     "expr": "sum(increase(marketplace_message_uploads_total{kubernetes_namespace=\"marketplace-ci\"}[24h]))",
     "legendFormat": "Report uploads over the last day"
    }
   ]
  },
  {
   "title": "Queued Reports & Slices",
   "type": "graph",
   "description": "Visualization of all of the queued reports & report slices",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(queued_report_slices{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Queued report slices"
    },
    {
     "expr": "sum(queued_reports{kubernetes_namespace=\"marketplace-ci\"})",
     "legendFormat": "Queued reports"
    },
    {
     "expr": "sum(increase(queued_report_slices{kubernetes_namespace=\"marketplace-ci\"}[1m]))",
     "legendFormat": "Queued report slices per minute"
    },
    {
     "expr": "sum(increase(queued_reports{kubernetes_namespace=\"marketplace-ci\"}[1m]))",
     "legendFormat": "Queued reports per minute"
    },
    {
     "expr": "sum(rate(queued_report_slices{kubernetes_namespace=\"marketplace-ci\"}[1m]))",
     "legendFormat": "Rate of queued report slices per minute"
    },
    {
     "expr": "sum(rate(queued_reports{kubernetes_namespace=\"marketplace-ci\"}[1m]))",
     "legendFormat": "Rate of queued reports per minute"
    }
   ]
  }
 ]
}