---
apiVersion: v1
kind: Template
metadata:
  name: marketplace
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: marketplace-tmp-claim
    labels:
      app: marketplace
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${VOLUME_CAPACITY}"
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: marketplace
  spec:
    envName: ${ENV_NAME}
    pods:
    - name: service
      image: ${IMAGE}:${IMAGE_TAG}
      minReplicas: ${{MIN_REPLICAS}}
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /api/marketplace/v1/status/
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 35
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 120
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /api/marketplace/v1/status/
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 35
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 120
      env:
      - name: DJANGO_SECRET_KEY
        valueFrom:
          secretKeyRef:
            key: django-secret-key
            name: marketplace-secret
            optional: false
      - name: MARKETPLACE_BUCKET
        value: ${MARKETPLACE_BUCKET}
      - name: RETRIES_ALLOWED
        value: ${RETRIES_ALLOWED}
      - name: PAUSE_KAFKA_FOR_FILE_UPLOAD_SERVICE
        value: ${PAUSE_KAFKA_FOR_FILE_UPLOAD_SERVICE}
      - name: NEW_REPORT_QUERY_INTERVAL
        value: ${NEW_REPORT_QUERY_INTERVAL}
      - name: CLOWDER_ENABLED
        value: ${CLOWDER_ENABLED}
      resources:
        limits:
          cpu: ${{CPU_LIMIT}}
          memory: ${MEMORY_LIMIT}
        requests:
          cpu: 500m
          memory: 512Mi
      web: true
      volumes:
      - name: marketplace-tmp
        persistentVolumeClaim:
          claimName: marketplace-tmp-claim
      volumeMounts:
      - name: marketplace-tmp
        mountPath: "/tmp"
    objectStore:
    - ${MARKETPLACE_BUCKET}
    kafkaTopics:
    - replicas: 3
      partitions: 10
      topicName: platform.upload.mkt
    dependencies:
    - ingress
    database:
      name: marketplace-db
      version: 10

parameters:
- name: MARKETPLACE_BUCKET
  value: marketplace-s3
- name: NEW_REPORT_QUERY_INTERVAL
  value: "60"
- name: PAUSE_KAFKA_FOR_FILE_UPLOAD_SERVICE
  value: "False"
- name: RETRIES_ALLOWED
  value: "5"
- name: RETRY_TIME
  value: "480"
- description: Volume space available for data, e.g. 512Mi, 2Gi
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: Cpu limit of service
  name: CPU_LIMIT
  value: "1"
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 1Gi
- name: MIN_REPLICAS
  value: "1"
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/marketplace
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "True"
- description: ClowdEnv Name
  name: ENV_NAME
  requred: false
