---
apiVersion: v1
kind: Template
metadata:
  name: marketplace
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: marketplace
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: service
      minReplicas: ${{MIN_REPLICAS}}
      web: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/marketplace/v1/status/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 120
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/marketplace/v1/status/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 35
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 120
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: marketplace-secret
              optional: false
        - name: MARKETPLACE_BUCKET
          value: ${MARKETPLACE_BUCKET}
        - name: RETRIES_ALLOWED
          value: ${RETRIES_ALLOWED}
        - name: PAUSE_KAFKA_FOR_FILE_UPLOAD_SERVICE
          value: ${PAUSE_KAFKA_FOR_FILE_UPLOAD_SERVICE}
        - name: NEW_REPORT_QUERY_INTERVAL
          value: ${NEW_REPORT_QUERY_INTERVAL}
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: HABERDASHER_EMITTER
          value: ${HABERDASHER_EMITTER}
        - name: HABERDASHER_KAFKA_BOOTSTRAP
          value: ${HABERDASHER_KAFKA_BOOTSTRAP}
        - name: HABERDASHER_KAFKA_TOPIC
          value: ${HABERDASHER_KAFKA_TOPIC}
        - name: HABERDASHER_LABELS
          value: ${HABERDASHER_LABELS}
        - name: HABERDASHER_TAGS
          value: ${HABERDASHER_TAGS}
        - name: ENABLE_CLOUDWATCH_LOGGING
          value: ${ENABLE_CLOUDWATCH_LOGGING}
        resources:
          limits:
            cpu: ${{CPU_LIMIT}}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: 500m
            memory: 512Mi
    objectStore:
    - ${MARKETPLACE_BUCKET}
    kafkaTopics:
    - replicas: 3
      partitions: 10
      topicName: platform.upload.mkt
    - replicas: 3
      partitions: 10
      topicName: platform.upload.validation
    dependencies:
    - ingress
    database:
      name: marketplace

parameters:
- name: MARKETPLACE_BUCKET
  value: marketplace-s3
- name: NEW_REPORT_QUERY_INTERVAL
  value: "60"
- name: PAUSE_KAFKA_FOR_FILE_UPLOAD_SERVICE
  value: "False"
- name: RETRIES_ALLOWED
  value: "5"
- name: RETRY_TIME
  value: "480"
- description: Cpu limit of service
  name: CPU_LIMIT
  value: "1"
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 1Gi
- name: MIN_REPLICAS
  value: "1"
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/marketplace
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "True"
- description: ClowdEnv Name
  name: ENV_NAME
  requred: false
- description: Emitter for haberdasher logs [stderr|kafka]
  name: HABERDASHER_EMITTER
  value: stderr
- description: Bootstrap server for haberdasher kafka emitter
  name: HABERDASHER_KAFKA_BOOTSTRAP
  value: ""
- description: Kafka topic for haberdasher kafka emitter
  name: HABERDASHER_KAFKA_TOPIC
  value: ""
- description: Haberdasher tags for unstrutured logs
  name: HABERDASHER_TAGS
  value: "[]"
- description: Haberdasher labels for unstructured logs
  name: HABERDASHER_LABELS
  value: "{}"
- description: Determines if Cloud Watch logging is enabled
  name: ENABLE_CLOUDWATCH_LOGGING
  value: "False"
